# Generated by Django 5.0 on 2024-06-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_apikey_delete_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='key',
            new_name='api_key',
        ),
    ]
