# Generated by Django 5.0 on 2024-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_key_apikey_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='remaining_requests',
            field=models.IntegerField(default=5),
        ),
    ]
