# Generated by Django 5.0 on 2024-08-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_apikey_remaining_requests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
